preload = ~/Pictures/wallpaper/active/now.png
wallpaper = eDP-1,~/Pictures/wallpaper/active/now.png


#wallpaper {
#    monitor = HDMI-A-1
#    path = $HOME/Pictures/wallpaper/active
#    fit_mode = cover
#    timeout = 900 
#}
#
#wallpaper {
#    monitor = DP-1
#    path = $HOME/Pictures/wallpaper/active
#    fit_mode = cover
#    timeout = 900 
#}
